BOT_NAME = 'scrapy_vuhizas_boilerplate'

SPIDER_MODULES = ['spiders']
NEWSPIDER_MODULE = 'spiders'


ROBOTSTXT_OBEY = False
COOKIES_ENABLED = False

TELNETCONSOLE_ENABLED = False


REACTOR_THREADPOOL_MAXSIZE = 20

AJAXCRAWL_ENABLED = True